name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17.0]  # Using Node.js 16.17.0

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install  # Ensures dependencies are installed

    - name: Run ESLint
      run: npm run lint  # Execute ESLint script

    - name: Run tests
      run: npm test  # Executes your test scripts

